apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one 
  ports:
  - name: http-otlp-grpc
    nodePort: 30003
    appProtocol: grpc
    port: 4317                                                                                                                                                        
    protocol: TCP                                                                                                                                               
    targetPort: 4317