apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-opentelemetry
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  endpoint: "http://otel-collector.vkpr:4318/v1/traces"
plugin: opentelemetry