apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
spec:
  type: NodePort
  selector:
    app: loki     
    release: loki   
  ports:
  - name: http-metrics
    nodePort: 30001
    appProtocol: grpc                                                                                                                                                    
    port: 3100                                                                                                                                                           
    protocol: TCP                                                                                                                                                        
    targetPort: 3100 