apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-stack-kube-prom-prometheus
  ports:
  - name: http-web
    nodePort: 30002
    appProtocol: grpc                                                                                                                                                    
    port: 9090                                                                                                                                                           
    protocol: TCP                                                                                                                                                        
    targetPort: 9090 